name: CI/CD - Sring Boot Test automation

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set op JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Spring Boot App
        run: gradle clean build